### ISSUE TITLE
Type constrain during evaluation

### ISSUE THREAD

**Issue by chocolate9624** [cheungdaven/QuatE#1]
Do you add the type constrain in all experiments?  
If it is true, I think it is not fair to compare with other methods, like RotatE. 

Thanks!

**Comment by chocolate9624** [comment]
I run your code and find your reported result of FB15K237 is "type constraint results".

**Comment by cheungdaven** [comment]
Type constraint has no effects on the performances. You can have a look at the reported performance of OpenKE. https://github.com/thunlp/OpenKE.
